### ISSUE TITLE
keys.json template

### ISSUE THREAD

**Issue by Dinip** [iGotYourBack/TimePlayed#5]
Can you please provide the template file for keys.json so I can fill with my tokens and logins to mysql?
Thanks

**Comment by Dinip** [comment]
and also need package.json to install the dependencies...

**Comment by Valentijnvw** [comment]
Hi,
I'm sorry for the late response, but if you're still interested I have made a full tutorial how to self-host the bot, including a keys.json template. You can check it out [here](https://github.com/xVaql/TimePlayed/wiki/Self-hosting), please let me know if you have any more issues.

**Comment by Dinip** [comment]
Oh nice! I opened this ticket since there was no information on how to self-host the bot! Thank you, I will check it out! Btw is it possible to host a private website like yours to show the status? Or do I need to make the website myself? 

Thanks!

**Comment by Valentijnvw** [comment]
Yes, it is possible but I won't fully support it or make a tutorial for that. The code for my website is available [here](https://github.com/xVaql/TimePlayed-Website), but please keep your website for private use only.
The basic setup for this would be:
1. Clone the code from the link above
2. Run `npm install discord.js express cookie-parser node-fetch btoa body-parser mysql` in the website folder
3. Create keys.json with the following template:
```
{
    "botToken": "(bot-token)",
    "clientSecret": "(bot-client-secret)",
    "clientId": "(bot-client-id)",
    "callbackUrl": "http://(your-ip-or-url)/callback",
    "mysqlhost": "localhost",
    "mysqluser": "root",
    "mysqlpasswd": "(mysql-password)",
    "schedule": false
}
```
You'll have to setup an oAuth application via [Discord Developers](https://discordapp.com/developers/applications/), set a callback url (with your domain name or server IP + `/callback`, e.a. for `http://timeplayed.xyz/callback`) and on that page you can also get your client secret for the oAuth login.
Please let me know if I missed anything or if you're having trouble!

**Comment by Dinip** [comment]
Nice I will try! And yes the website is just for private use. I own a discord server with some friends and we wanted to do something like a "player of the week" based on hours player, so I found your bot! The website makes the things easier to see!

Thank you and keep the good work! 🥇

**Comment by Dinip** [comment]
btw there is an error on keys.json example on the tutorial. ("self-host": true,) should be ("selfHost": true,)
I was getting "Error: Cannot find module 'dblapi.js'".
![image](https://user-images.githubusercontent.com/8941012/51199829-bbe35900-18ef-11e9-8355-c790b446512d.png)

**Comment by Valentijnvw** [comment]
Thanks for letting me know, I updated the wiki, it should work now
